default: &default
  host: localhost
  user: thays
  password: 10934912
  adapter: postgres

development:
  <<: *default
  db: code_challenge_development

test:
  <<: *default
  db: code_challenge_test

production:
  <<: *default
  db: code_challenge_production